[package]
name = "webchat-client-rs"
version = "0.1.0"
authors = ["Teemu Erkkola <teemu.erkkola@iki.fi>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
webchat-rs = { path = ".." }

[profile.release]
opt-level = 'z'
lto = true
panic = 'abort'

